# Generated by Django 5.1.6 on 2025-03-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parquetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienEntreFichiersParquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('file_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_1', to='parquetapp.parquetfile')),
                ('file_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_2', to='parquetapp.parquetfile')),
            ],
        ),
    ]
