# Generated by Django 5.1.6 on 2025-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parquetapp', '0002_lienentrefichiersparquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquetfile',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
