# Generated by Django 5.1.6 on 2025-03-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parquetapp", "0003_parquetfile_alias"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lienentrefichiersparquet",
            old_name="file_2",
            new_name="parquet_file_left",
        ),
        migrations.RenameField(
            model_name="lienentrefichiersparquet",
            old_name="file_1",
            new_name="parquet_file_right",
        ),
        migrations.CreateModel(
            name="ParquetFileColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data_type_from_vcf", models.CharField(max_length=255)),
                ("data_type_from_duckdb", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "parquet_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="parquetapp.parquetfile",
                    ),
                ),
            ],
        ),
    ]
