# Generated by Django 5.1.6 on 2025-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parquetapp",
            "0005_alter_lienentrefichiersparquet_parquet_file_left_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parquetfile",
            name="original_vcf_file_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
